import { StyleSheet } from 'react-native';
import { scaleFont, scaleHeight, scaleMargin, scalePadding, scaleWidth } from '../../utils/scale';
import { BACKGROUND_COLOR, COLOR_CODE, COLOR_PALETTE, TEXT_COLOR } from '../../types/enums';

const styles = StyleSheet.create({
  recipesCardContainer: {
    flex: 1,
    backgroundColor: BACKGROUND_COLOR.PRIMARY,
  },
  container: { display: 'flex', flexDirection: 'row', justifyContent: 'space-between', margin: scaleMargin(15) },
  spaceBetween: { display: 'flex', flexDirection: 'row', justifyContent: 'space-between' },
  textUp: {
    fontSize: scaleFont(15),
    color: COLOR_PALETTE.APACHE,
    borderWidth: 2,
    borderColor: COLOR_PALETTE.SEASHELL,
    backgroundColor: COLOR_PALETTE.SEASHELL,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 2,
  },
  textDown: {
    fontSize: scaleFont(15),
    color: COLOR_PALETTE.APACHE,
    borderWidth: 2,
    borderColor: COLOR_PALETTE.SEASHELL,
    backgroundColor: COLOR_PALETTE.SEASHELL,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 2,
    textAlign: 'center',
    marginTop: 10,
  },
  addPhotoContainer: { height: scaleHeight(200), borderColor: COLOR_PALETTE.SEASHELL, borderWidth: 2, margin: scaleMargin(10), borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  addPhotoImage: { height: scaleHeight(25), width: scaleWidth(25) },
  drinkInfoContainer: {
    backgroundColor: COLOR_PALETTE.SEASHELL,
    padding: scalePadding(12),
    borderRadius: 12,
    margin: scaleMargin(12),
    shadowColor: COLOR_PALETTE.DRIFTWOOD,
    shadowOffset: { width: scaleWidth(-2), height: scaleHeight(4) },
    shadowOpacity: 0.9,
    shadowRadius: 3,
    elevation: 6,
  },
  drinkInfoContainerMarginDown: { marginBottom: scaleMargin(20), fontSize: 13 },
  ft700: { fontWeight: '700' },
  moreAndQuantityContainer: { display: 'flex', flexDirection: 'row', marginTop: scaleMargin(12) },
  moreAndQuantityTextCont: { display: 'flex', flexDirection: 'row', gap: 10, marginLeft: scaleMargin(15) },
  moreAndQuantityText: { borderRadius: 20, borderWidth: 1, borderColor: COLOR_CODE.PRIMARY, paddingHorizontal: scalePadding(10), alignSelf: 'center' },
  moreIcon: { height: scaleHeight(40), width: scaleWidth(60), marginTop: scaleMargin(10) },
  moreAndQuantityImageText: { marginHorizontal: scaleMargin(15), alignSelf: 'center' },
  ingredientsText: { marginLeft: scaleMargin(15), marginVertical: scaleMargin(15), display: 'flex', flexDirection: 'row', justifyContent: 'space-between' },
  sublistContainer: { padding: scalePadding(5) },
  sublistBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderColor: TEXT_COLOR.GRAY2,
  },
  sublistName: {
    fontSize: scaleFont(13),
    paddingBottom: scalePadding(5),
    marginLeft: scaleMargin(10),
    paddingVertical: scalePadding(10),
    color: BACKGROUND_COLOR.BLACK,
  },
  ratingContainer: { backgroundColor: COLOR_PALETTE.APACHE, borderRadius: 10, marginHorizontal: scaleMargin(10), paddingHorizontal: scalePadding(5) },
  ratingImage: { alignSelf: 'center', marginRight: scaleMargin(5) },
  labelContainer: { padding: scalePadding(10) },
  labelButton: { display: 'flex', flexDirection: 'row', justifyContent: 'space-between', gap: 20 },
  editOptionContainer: {
    height: scaleHeight(40),
    justifyContent: 'flex-end',
    marginBottom: scaleMargin(20),
  },
  editOptionBox: {
    alignSelf: 'center',
    display: 'flex',
    flexDirection: 'row',
    gap: 10,
  },
  editOptionText: {
    fontSize: scaleFont(12),
    backgroundColor: COLOR_PALETTE.SEASHELL,
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: scalePadding(30),
    paddingVertical: scalePadding(5),
    borderColor: COLOR_PALETTE.APACHE,
    shadowOffset: { width: scaleWidth(-2), height: scaleHeight(4) },
    shadowOpacity: 0.9,
    shadowRadius: 3,
    elevation: 6,
  },
});

export default styles;
