export const STRINGS = {
  ADD: 'Add',
  AMAZING: 'Amazing',
  AND_ESSENTIALS: 'And Essentials',
  AS: 'As',
  BACK: 'Back',
  BADGES_COLLECTED: 'Badges Collected',
  BREW: 'Brew',
  BREWMASTER: 'Brewmaster',
  BREWPOD: 'Brewpod',
  BREWS: 'Brews',
  BRIX: 'Brix',
  BUY: 'Buy',
  BUY_YOUR_OWN: 'Buy your own',
  BY: 'By',
  CANCEL: 'Cancel',
  CLASSIC: 'Classic',
  CLEANING: 'Cleaning',
  CONNECT: 'Connect',
  CONNECT_YOUR_BREWPOD: 'Connect your Brewpod',
  CREATE: 'Create',
  CREATE_PROFILE: 'Create Profile / Log In',
  CURRENT_BREW: 'Current Brew',
  DELETE: 'Delete',
  DEVICE: 'Device',
  DRAFTS: 'Drafts',
  EDIT: 'Edit',
  EMAIL: 'Email',
  ENTER_YOUR_EMAIL_ID: 'Enter Your Email Id',
  ENTER_YOUR_NAME: 'Enter Your Name',
  ESTIMATED_TIME_OF_COMPLETION: 'Estimated time of completion',
  EXPLORE: 'Explore',
  FAVORITE_STYLE: 'Favorite Style',
  FERMENTATION: 'Fermentation',
  FLOATY: 'Floaty',
  FOR: 'For',
  GOOGLE: 'Google',
  HOPS: 'Hops',
  HOURS: 'Hours',
  INGREDIENTS: 'Ingredients',
  INSTAGRAM: 'Instagram',
  LAGERS: 'Lagers',
  LAGER: 'Lager',
  LETS: "Let's",
  PREPARE: 'Prepare',
  LIVE_STATUS: 'Live Status',
  LOGIN: 'Login',
  MY: 'My',
  MY_BREWPOD: 'My Brewpod',
  NAME: 'Name',
  NEW: 'New',
  OFFLINE: 'Offline',
  ONLINE: 'Online',
  OR_LOGIN_WITH: 'Or Log In with',
  OVERALL_PROGRESS: 'Overall Progress',
  PHOTO: 'Photo',
  POST_ON_COMMUNITY: 'Post on Community',
  PREVIOUS: 'Previous',
  PROFILE: 'Profile',
  PROFILE_NAME: 'Ninja Brewer',
  QR_CODE: 'QR Code',
  RECIPES: 'Recipes',
  RECIPE: 'Recipe',
  SAVE: 'Save',
  SAVED: 'Saved',
  SCAN: 'Scan',
  SEARCH: 'Search',
  SHARE: 'Share',
  SHARE_ON: 'Share on',
  SHARE_PROGRESS: 'Share progress',
  SHARE_YOUR_STATUS: 'Share your status',
  SHOW_LESS: 'Show less',
  STATUS: 'Status',
  STRONG: 'Strong',
  STRONG_LAGER: 'Strong Lager',
  TIME: 'Time',
  TO: 'To',
  TOTAL_BREWS: 'Total Brews',
  TRACK_YOUR_PROGRESS: 'Track your progress',
  UNLEASH: 'Unleash Your Inner',
  UNLEASH_UNBROKEN: 'Unleash Your Inner',
  WELCOME_BACK: 'Welcome back',
  YOU: 'You',
  YOUR: 'Your',
  YOUR_OWN_RECIPES: 'Your Own Recipes',
  TOKEN_KEY: 'AuthToken',
  USER_DETAILS: 'UserDetails',
  MORE: 'More',
  PICTURE: 'Picture',
};
